FROM ubuntu:bionic

RUN apt-get update\
  # Basic developer tools
  && apt-get install -y --no-install-recommends\
      make\
      build-essential\
      wget\
      python-dev

RUN wget http://apps.fz-juelich.de/scalasca/releases/cube/4.5/dist/cubelib-4.5.tar.gz\
  && tar -xf cubelib-4.5.tar.gz\
  && cd cubelib-4.5\
  && ./configure --prefix=/opt/\
  && make -j4 install

    
